# Use an official Node.js image as the base
FROM node:latest

# Set the working directory in the container
WORKDIR /app/client

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the client code
COPY . .

# Specify the command to run the front-end application
CMD ["npm", "run", "dev"]
